### ISSUE TITLE
Lab Period #1 - Project Brainstorm

### ISSUE THREAD

**Issue by juliaeveritt** [UBC-MDS/hexdropper#1]
Project Idea
* We will create an eyedropper tool that allows users to determine the hex colour code by inputting a cropped image

Function Breakdown
* Function to read image (impose constraints on image size). Input: jpg image, output: numpy array of RGB values - Julia
* Function to determine the most common RGB value in the image. Input: numpy array of RGB values, output: a single RGB value - Mona
* Function to convert RGB to hex (see this website for formula: https://gristle.tripod.com/hexconv.html). Input: RGB value, output: hex code - Joey
* Function to output the hex code and a figure in that colour. Input: hex code, output: image with hex code as text displayed to user - hancheng

Language
* We will be using Python

**Comment by monazhu** [comment]
A few additional things we need to do for this milestone: 

- Project board - @monazhu 
- `CONDUCT.md` to include the code of conduct for contributing to your project (we can use one from DSCI 522 as template)
- `CONTRIBUTING.md` - @monazhu 
- `README.md` (specifically, (1) a high level paragraph summarizing project package, (2) a bullet point of 1-2 sentence describing the proposed functions and (3) a paragraph describing where your packages fit into the Python ecosystem (are there any other Python packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well)

Once you've had time to review the details for milestone 1 (https://pages.github.ubc.ca/MDS-2023-24/DSCI_524_collab-sw-dev_students/release/milestone1/milestone1.html), let me know which of the remaining tasks you'd like to take on and I can update this comment with the assignment :)

**Comment by hchqin** [comment]
Joey and I can take the remaining two tasks. 
Joey will finish`README.md` to cover the topics mentioned above and I will finish `CONDUCT.md`.
