### ISSUE TITLE
Create test and complete function for `rgb_to_hex`

### ISSUE THREAD

**Issue by monazhu** [UBC-MDS/hexdropper#19]

**Comment by monazhu** [comment]
Just bringing this discussion over from slack just so we're tracking. @joeywwwu i realized that since you're going to be using the output of my function as your input. the output of my function can only be a single object, rather than 3 objects as indicated in your function, so you may need to modify your input parameters. 

Currently, my output is a tuple, but i can turn it into a list or dictionary - let me know which of them will work best for you and i can adjust my code accordingly!

**Comment by joeywwwu** [comment]
@monazhu  Actually I have thought about whether to make function input to single or three objects too. Tuple output works well, I assume your tuple output would be like (255, 255, 255), I am thinking that the user would copy the RGB code without parentheses. If they do with parentheses, the function would looks like rgb_to_hex((255,255,255)), which is kind of discordant. I’m also thinking that the users may just use the function alone. But I understand in some cases when the user enter a variable rgb_to_hex(some-variable), inputting the tuple may work better in this situation. What about making the function support both ways of input, including rgb_to_hex((255,255,255)) and rgb_to_hex(255,255,255)? It offers better flexibility in input.

**Comment by monazhu** [comment]
Yes, that sounds good! I've pushed my function and tests through (the output is a tuple with the R, G, and B values respectively)
