### ISSUE TITLE
Running pytest

### ISSUE THREAD

**Issue by juliaeveritt** [UBC-MDS/hexdropper#22]
Hi team! Just pushed my unit tests/some sample images to feat-read-img-m2 branch. The tests pass when I run them individually but I'm having trouble running pytest properly - getting the error `importlib.metadata.PackageNotFoundError: hexdropper`. Let me know if anyone else runs into this please!

**Comment by juliaeveritt** [comment]
Joey helped with this over slack! Copying his response here for reference:

The issue is  __init__.py file inside the src/hexdropper directory, it’s trying to use importlib.metadata.version to get the version of a package that is not installed. If hexdropper is just a Python file and not an installed package, this approach won’t work. So, I change the __version__ = "0.1.0" in  __init__.py file, and it works.

**Comment by monazhu** [comment]
Just a quick update on this after running into this issue again myself (even after changing the files as Joey had suggested) - the version in the `__init__.py` file should remain as is (i.e., we shouldn't be changing the version number manually as that should get updated in the project's toml file. Tiffany had mentioned this in lecture 3). What seemed to be the issue was that the package dependencies were not updated in the toml file. 

To get around this issue, I ran the following: 

1. `poetry install`
2. `poetry add [package name]`
3. `poetry add --group dev pytest`
5. `pytest tests/` 

Would appreciate it if someone else can confirm whether this worked for them or not!

**Comment by joeywwwu** [comment]
I'm stuck with the `poetry add hexdropper` , it report an error saying 'Could not find a matching version of package hexdropper'. I will go check tiff's video and see if it will work. **But I did merge py file with manual changes to main, do I need to change it back?** @monazhu

**Comment by monazhu** [comment]
@joeywwwu I don't think you can add hexdropper just yet because we haven't built the actual package (we'll need to do this at the very end). by point 2 (`poetry add [package name]`) I just meant say, if you used matplotlib, then you need to include `poetry add matplotlib`

**Comment by monazhu** [comment]
Were you able to run `pytest tests/` without any errors before pushing your changes through? If so, I think that's all that matters

**Comment by joeywwwu** [comment]
Okay, I see what you mean. I will run pytest tests/ and see how it goes.

**Comment by joeywwwu** [comment]
I run `pytest tests/`, it raises` PackageNotFoundError`, but the package that is not found is `hexdropper`. It is still the same error as before.

**Comment by monazhu** [comment]
Can you tell me what you did before running `pytest tests/`? Also - did you pull the changes from the remote repo with the updated poetry.lock file as well as pyproject.toml file? I'm just trying to understand how to reproduce your steps

**Comment by monazhu** [comment]
@joeywwwu I think I see what the issue is. I just pulled the repo with your updated functions and tests and it worked on my end. Here's what I did:

1. in the `__init__.py` file, switch back to using `__version__ = version("hexdropper")`
2. ran `poetry install`
3. ran `pytest tests/`

this is my output: 
![image](https://github.com/UBC-MDS/hexdropper/assets/7615983/04d76063-1d09-4db3-9ecd-81baaea72b6e)

**Comment by joeywwwu** [comment]
I see, thanks a lot @monazhu ! I will do as you suggest!

**Comment by joeywwwu** [comment]
@monazhu after pulling from remote repo and running as you suggest, it still raises the same error from my end. Three errors raised from three functions are all about `ModuleNotFoundError: No package metadata was found for hexdropper`
 
![image](https://github.com/UBC-MDS/hexdropper/assets/143630759/a3e67b16-610e-4d4c-809e-786906168187)

**Comment by monazhu** [comment]
were you able to run `poetry install` okay? You should get a message saying the following: 

![image](https://github.com/UBC-MDS/hexdropper/assets/7615983/d731cd9f-7e09-423a-a137-125e7c36de11)

**Comment by joeywwwu** [comment]
Yes, I do.
![image](https://github.com/UBC-MDS/hexdropper/assets/143630759/2d4a6692-8850-4682-a61f-5f8dc8e426ea)

**Comment by monazhu** [comment]
okay this is a long shot - but did you save your `__init__.py` file after making the changes?

**Comment by joeywwwu** [comment]
yes

**Comment by monazhu** [comment]
hmm... okay I'm kind of at a loss right now. I think it's a little hard to try and debug the issue remotely without seeing your files - would you be okay jumping on a quick videocall later today over slack and I can try and debug then?

**Comment by monazhu** [comment]
In the mean time I'm just going to update the `__init__.py` file on main to fix the issue with version

**Comment by joeywwwu** [comment]
@juliaeveritt Hey Julia, I found that there is a `KeyError` in `test_read_image.py` on my end, when running the `pytest tests/`. It seems like there is a slash issue with the file path on line 9 and 10. `\\` may not work on Mac, but it works when I change it to `/`. Mona had tested using `/` on her windows, and it works. I wondering if `/` will work on your end. If it works for both Mac and windows, would you mind changing `\\` to `/`? 

This is my changes on my local repo: 
![image](https://github.com/UBC-MDS/hexdropper/assets/143630759/f2e917d4-f4ad-4421-a644-8c6f920939dc)

I could push my changes to the remote repo too, if you'd like! Thanks!

**Comment by juliaeveritt** [comment]
Final communication on this was done on slack - we did change `\\` to `/`. Closing issue!
