### ISSUE TITLE
Compile the package

### ISSUE THREAD

**Issue by joeywwwu** [UBC-MDS/hexdropper#33]
Also make sure all function documentation should be rendered using the napolean Sphinx extension and readable on [ReadTheDocs](https://about.readthedocs.com/?ref=readthedocs.com).

updates it 
<img width="685" alt="image" src="https://github.com/UBC-MDS/hexdropper/assets/143630759/dead26c4-d14d-4cc3-b0e3-3302c7a5ca14">

**Comment by monazhu** [comment]
Closing this issue as task has been completed
