### ISSUE TITLE
Hexdropper Tutorial: Describing usage for `most_common_rgb`

### ISSUE THREAD

**Issue by monazhu** [UBC-MDS/hexdropper#34]
Explain how to use the `most_common_rgb` function and motivate the reason why we chose to most common rgb

**Comment by joeywwwu** [comment]
Hi @monazhu , may I confirm whether the section `Use the hexcode to create complimentary visualizations for your project!`  is followed by the `most_common_rgb` tutorial or is served as the ending of our document? It seems ending to me as it assumes "having the hexcode of that logo". Thanks!

**Comment by monazhu** [comment]
Julia made that section and I think based on the narrative, that section is
supposed to go at the very end (e.g., we use this colour in a plot now that
we have the hex code)

**Comment by joeywwwu** [comment]
Got it! Thanks!

**Comment by joeywwwu** [comment]
<img width="793" alt="image" src="https://github.com/UBC-MDS/hexdropper/assets/143630759/a829a728-33e3-463b-b5fe-da860e6c6bed">
@monazhu, I noticed there is a small typo with the input `B` in the picture. If you'd like, I would be happy to correct it. But I'm not sure about the interface in the picture, is it in Word or some other software? Thanks!

**Comment by monazhu** [comment]
Oh, thanks so much for catching that! I just googled a RGB colour picker
and took a screenshot - if you wouldn't mind replacing the image with one
with the correct values, I'd super appreciate it! 🙏♥️

This is the site I used by the way!
https://www.rapidtables.com/web/color/RGB_Color.html

**Comment by joeywwwu** [comment]
Of course, no problem! 👍

**Comment by monazhu** [comment]
Checked over section in `example.ipynb` - will close and mark task as completed! Thanks again @joeywwwu :)
