### ISSUE TITLE
Fix: valid input file types

### ISSUE THREAD

**Issue by juliaeveritt** [UBC-MDS/hexdropper#50]
I noticed my original tests allowed for both .jpg and .png images, which is not accurate currently as subsequent steps require 3d input. I can either modify read_image to return only the RGB channels, or add a check to only accept .jpg images (.jpg has RGB channels, .png has RGB and alpha channels)

**Comment by juliaeveritt** [comment]
Hey @monazhu! I looked into cv2.imread and it seems by default cv2.imread ignores the alpha channel on png images. When I did some testing using our functions, I found I got the same result passing the png and jpg into most_common_rgb! On my end it's looking like we can leave as is and update the example .ipynb, could you let me know if you are still finding the output differs?

**Comment by juliaeveritt** [comment]
Actually it's a very small difference - (8, 181, 212) for png and (8, 181, 213) for jpg. Looks practically the same on colour wheel. Weird

**Comment by monazhu** [comment]
@juliaeveritt okay yes that explains the difference in the RGB values - because I'd noticed it was jumping around a little bit. Okay, but it's good news that it somehow just knows to convert PNG files into 3-channel inputs rather than the 4 channel inputs. Maybe what we can do is just edit the `example.ipynb` file to reflect this and not worry about the PNG/JPG difference

**Comment by monazhu** [comment]
If you're okay with that plan, I can go ahead and update `example.ipynb` on my end!

**Comment by juliaeveritt** [comment]
I think it may be due to the fact that png is a 'lossless' file format and jpg is not https://www.holisticseo.digital/technical-seo/jpg-png-difference/. I agree!

**Comment by monazhu** [comment]
Okay sounds good! I'll go ahead and edit `example.ipynb` on my end :)

**Comment by juliaeveritt** [comment]
Oo interesting - I tried comparing the outputs with the cropped image and png and jpg (used uncropped before), and output is exactly the same! Think this confirms it's just related to file compression, maybe some blurring of the blue and uncropped white pixels

**Comment by juliaeveritt** [comment]
Sounds good! I'll add an extra test case for this and push. Thanks Mona!

**Comment by monazhu** [comment]
Thanks for looking into this Julia! Now we know cv2 is much better at handling different image types than matplotlib haha!

**Comment by juliaeveritt** [comment]
Hahaha matplotlib is really not our friend on this package ...
