### ISSUE TITLE
Feedback: Example File - Place image in the section of Read image instead of beginning

### ISSUE THREAD

**Issue by juliaeveritt** [UBC-MDS/hexdropper#51]
1:  Place image in the section of Read image instead of beginning for better readability

**Comment by juliaeveritt** [comment]
2: Show the image created in the section of 'Export the extracted color'

**Comment by juliaeveritt** [comment]
3: Include corresponding function name in headlines

**Comment by juliaeveritt** [comment]
4: Add monospace font into the headings to enhance readability

**Comment by monazhu** [comment]
5: Provide motivation for example use cases for when most common/frequent colours are preferred.

**Comment by monazhu** [comment]
`example.ipynb` has been updated with the following changes to address reviewer comments: 
- Motivation for the use of extracting most common/frequent colour in a cropped image has been added to the introduction section (point 5); example provided has also been updated to more clearly highlight the use case / motivation for doing so
- Corresponding function names and monospace fonts in headings have now been added to address points 3 and 4
- The image being used has now been moved under the section for `read_image` to enhance readability (point 1)
- Corresponding output image has now been added to the final section of the tutorial
