### ISSUE TITLE
Feedback: README file

### ISSUE THREAD

**Issue by joeywwwu** [UBC-MDS/hexdropper#52]
1. Add other badges needed

**Comment by joeywwwu** [comment]
2. Change install instruction conda create --name hexdropper python=3.9 -y in terminal.

**Comment by joeywwwu** [comment]
3. Code provided to activate environment, following poetry install

**Comment by joeywwwu** [comment]
4. Code provided for testing is- $ pytest tests/ --cov=pycounts.

**Comment by joeywwwu** [comment]
To help us easily, and correctly, assess this, please use create the commit messages that address the feedback something like this:

fix: Feedback addressed by ...

**Comment by joeywwwu** [comment]
5. The function use instructions in the README.md instruct the user to run the code read_image.read_image(), however this did not work for me. I believe it should be replaced with read_image()

**Comment by joeywwwu** [comment]
6. The documentation in the README.md also refer to a variable hex_code but this is never created. I tried to run the code literally and got an error. You could rectify this by adding a line where you store the result of rgb_to_hex() as hex_code, as you did in your vignette.

**Comment by monazhu** [comment]
@joeywwwu, you might already be aware of this, but I just realized that we might need to update/change the installation instructions now that our package is on PyPI (rather than the current developer's installation instructions we have right now).

**Comment by joeywwwu** [comment]
@monazhu thanks for reminding me! I will add a section on Installation for Users in Readme!
